#!/bin/bash

dir=`pwd`
repobase=`basename ${dir}`

git init
git add .
git commit -m "initial commit"
git remote add origin https://github.com/dfwskyview/${repobase}.dfwskyview.com.git
git push -u origin master

git remote add linuxtrader git@github.com:linuxtrader/${repobase}.dfwskyview.com.git
git pull linuxtrader master --allow-unrelated-histories
git push linuxtrader master

# Then 
#git push
#git push linuxtrader


