#! /bin/bash

DIST=EGD1ZS1L8R0M7

# Seperate
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/sb_data/*"
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/cf_data/CelinaSafety_Samples.zip"
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/cf_data/CelinaSafety01*"

# Do Together
 aws cloudfront create-invalidation --distribution-id ${DIST} --paths /videomobile.html /index.html /publish-hashes.json 
 aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/assets/*"

