#!/bin/bash


# youtube link to splash video https://youtu.be/Nyk_x_rmYdY

# cant use --delete here since there is more than one source directory.
# --acl public-read probably does nothing here since I have public set as brute force.

mv .git ../sb_git
aws s3 sync ~/Documents/aws/clients/celinasplash2018 s3://celinasplash18.dfwskyview.com/ --acl public-read 
mv ../sb_git .git

aws s3 sync            ~/Movies/clients/celinasplash s3://celinasplash18.dfwskyview.com/ --acl public-read --cache-control max-age=31536000,public

echo Maybe do zip -r ../celinasplash01.zip .
