#!/bin/bash


# youtube link to splash video https://youtu.be/Nyk_x_rmYdY

# cant use --delete here since there is more than one source directory.

mv .git ../sb_git
aws s3 sync ~/Documents/aws/clients/celinasplash2018 s3://celinasplash2018.dfwskyview.com/ 
mv ../sb_git .git

aws s3 sync ~/Movies/clients/celinasplash s3://celinasplash2018.dfwskyview.com/ 

echo Maybe do zip -r ../celinasplash01.zip .
